controller_list:
  - name: fake_left_ur_arm_controller
    joints:
      - left_ur_arm_shoulder_pan_joint
      - left_ur_arm_shoulder_lift_joint
      - left_ur_arm_elbow_joint
      - left_ur_arm_wrist_1_joint
      - left_ur_arm_wrist_2_joint
      - left_ur_arm_wrist_3_joint
  - name: fake_right_ur_arm_controller
    joints:
      - right_ur_arm_shoulder_pan_joint
      - right_ur_arm_shoulder_lift_joint
      - right_ur_arm_elbow_joint
      - right_ur_arm_wrist_1_joint
      - right_ur_arm_wrist_2_joint
      - right_ur_arm_wrist_3_joint
  - name: fake_manipulator_controller
    joints:
      - left_ur_arm_shoulder_pan_joint
      - left_ur_arm_shoulder_lift_joint
      - left_ur_arm_elbow_joint
      - left_ur_arm_wrist_1_joint
      - left_ur_arm_wrist_2_joint
      - left_ur_arm_wrist_3_joint
      - right_ur_arm_shoulder_pan_joint
      - right_ur_arm_shoulder_lift_joint
      - right_ur_arm_elbow_joint
      - right_ur_arm_wrist_1_joint
      - right_ur_arm_wrist_2_joint
      - right_ur_arm_wrist_3_joint
  - name: fake_right_hand_1_controller
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
  - name: fake_right_hand_2_controller
    joints:
      - joint_12
      - joint_13
      - joint_14
      - joint_15
  - name: fake_right_hand_3_controller
    joints:
      - joint_4
      - joint_5
      - joint_6
      - joint_7
  - name: fake_right_hand_4_controller
    joints:
      - joint_8
      - joint_9
      - joint_10
      - joint_11